apiVersion: v1
kind: Pod
metadata:
  name: duplicate-pod
  labels:
    type: duplicate
spec:
  containers:
  - name: duplicacte-container
    image: duplicate-2
    command: ["python3 duplicate.py"]
    args: ["/opt"]
 
